import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Wrapper } from '../components/Wrapper'
import NextNProgress from 'nextjs-progressbar'

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <Wrapper>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"
                />
                <link rel="icon" href="/favicon.ico" />
                <title>_</title>
            </Head>

            <Component {...pageProps} />

            <NextNProgress
                color="#29D"
                startPosition={0.3}
                stopDelayMs={200}
                height={3}
                showOnShallow={true}
            />
        </Wrapper>
    )
}
export default MyApp
